### ISSUE TITLE
The compiled executable demo is invalid

### ISSUE THREAD

**Issue by zxy-bjtu** [yixin26/Mesh-Segmentation#1]
Hello , the link (http://yixina.net/projects/FeatureSeg/FeatureSeg_demo.zip )of the compiled executable demo is invalid. Can you share this demo in another link? Thanks!

**Comment by yixin26** [comment]
Hi,

Check this link:  [https://yixin26.github.io/projects/FeatureSeg/FeatureSeg_demo.zip](https://yixin26.github.io/projects/FeatureSeg/FeatureSeg_demo.zip)
